version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "6379:6379"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdevdata:/data/db

volumes:
  dbdevdata: